{% set name = "arcp" %}
{% set version = "0.2.1" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stain/arcp-py/archive/{{ version }}.tar.gz
  sha256: 8a0058361c24f8e4ec7280f493d5b0a9fee3330ce8c38d439e6ef6c25a769e6f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - arcp
    - arcp.generate
    - arcp.parse
  source_files:
    - tests/test_generate.py
    - tests/test_parse.py
  commands:
    - python -m unittest tests/test_generate.py
    - python -m unittest tests/test_parse.py

about:
  home: https://github.com/stain/arcp-py
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Create/parse arcp (Archive and Package) URIs.
  description: |
    arcp provides functions for creating arcp URIs, which can be
    used for identifying or parsing hypermedia files packaged in an archive
    or package, like a ZIP file.

extra:
  recipe-maintainers:
    - pvanheus
